### PR TITLE
Hash hotspots output filenames

### LINKED ISSUE #246: Should not throw a `Errno::ENAMETOOLONG` for too long names.
It generates its own names and can generate too long names. 

E.g. a file called `/home/user/projects/some_rediculously_long_projectname/db/migrate/20140819122639_move_quantity_from_library_to_conversion_factor_and_expressions_indicator_builder.rb` is, indeed a stupid name. But it just so happens our project has this name. This results in an error:

    /home/user/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/metric_fu-4.11.1/lib/metric_fu/io.rb:117:in `initialize': File name too long @ rb_sysopen - /home/user/Documenten/some_project/tmp/metric_fu/output/_home_user_some_project_name_that_is_too_long_db_migrate_20140819122639_move_quantity_from_library_to_conversion_factor_and_expressions_indicator_builder.rb.html (Errno::ENAMETOOLONG)

(note, filenames are edited due to privacy and disclosure-issues)

### PR DESCRIPTION
**Pull request by MGotink**
This prevents 'File name too long @ rb_sysopen - long_file_name.rb.html (Errno::ENAMETOOLONG)' exception when hotspots it trying to save its output.
Closes #246.

### CODE REVIEW

File: lib/metric_fu/templates/metrics_template.rb [hunk 1]
```diff
@@ -23,6 +23,11 @@ def write
       write_file_data
     end
 
+    def html_filename(file)
+      file = Digest::SHA1.hexdigest(file)
+      "#{file.gsub(%r{/}, '_')}.html"
+    end
```
Comment (bf4) [inline lib/metric_fu/templates/metrics_template.rb]: I like the helper.  couldn't we just truncate it?  `"#{file.gsub(%r{/}, '_')[0..30]}".html"`

Comment (MGotink) [inline lib/metric_fu/templates/metrics_template.rb]: Why would we? It saves only 10 characters.

Comment (bf4) [inline lib/metric_fu/templates/metrics_template.rb]: just to make it more readable...

Comment (MGotink) [inline lib/metric_fu/templates/metrics_template.rb]: Hashes are not meant to be readable ;)
But I've implemented your suggestion.

**Comment by bf4** [comment]
I haven't run this locally but I trust you to merge if it's good.

**Comment by MGotink** [comment]
Ok, thanks!
